version: '3'

vars:
  NAME: "shared"
  PACKAGE_NAME: "github.com/hoomy-official/go-shared"
  PACKAGES: "pkg"

includes:
  default: https://raw.githubusercontent.com/hoomy-official/taskfile-default/main/tasks.yaml
  git: https://raw.githubusercontent.com/hoomy-official/taskfile-git/main/tasks.yaml
  markdownlint: https://raw.githubusercontent.com/hoomy-official/taskfile-markdownlint/main/tasks.yaml
  golangci: https://raw.githubusercontent.com/hoomy-official/taskfile-golangci/main/tasks.yaml

dotenv:
  - .env
  - .env.default